### ISSUE TITLE
Could you add docs about how to filter user input with query? or bot example 

### ISSUE THREAD

**Issue by asamsulfat** [kata-ai/kata-platform-docs#23]

**Comment by asamsulfat** [comment]
[query user input](http://i.imgur.com/dtMNRHF.png)

How to separate total ticket, destination place and ticket time from 1 chat?

I just know how to do 1 thing,

Ask how much ticket?
user replie (1)
Ask from where and go to where?
user replie (sby-jkt)

I want to know how to query user input
'Pesan tiket 1 dari sby-jakarta besok senin'

**Comment by prakashdivyy** [comment]
You can use knowledge from NL Studio to extract that information by following this tutorial https://docs.kata.ai/tutorial/nl-studio/

To integrate the NL that you already created with Bot Studio you can follow this tutorial https://docs.kata.ai/tutorial/bot-studio/
